name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - name: Hello world       # Name of step
      run: echo 'Hello world' # Command to run
    - name: Hello world Modified
      uses: actions/hello-world-javascript-action@v1.1 # Name of the action. This uses https://github.com/actions/hello-world-javascript-action
      with:                                            # This section is needed if you need to pass arguments to the action
        who-to-greet: 'Mona the Octocat'
    - name: Build and test C# and Typescript code
      working-directory: ./../DevOps-Course-Workshop-Module-07-Learners
      run: |
       dotnet build
       dotnet test
       cd DotnetTemplate.Web
       npm install
       npm run build
       npm run lint
       npm t
       cd ..
       docker build --tag madhuaxp/dotnettemplate .
       docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
       docker push madhuaxp/dotnettemplate
     - name: Login to Heroku Container registry
       env:
         HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY }}
       run: heroku container:login
     - name: Build and push
       env:
         HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY }}
       run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web
     - name: Release
       env:
         HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY }}
       run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web

       
    
